---
- name: Updating apt repo/cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  become: true

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: yes
    force_apt_get: yes
  become: true

- name: Uninstall some Packages
  ansible.builtin.apt:
    name:
      - enum4linux
    state: absent
  become: true

- name: Installing Packages
  ansible.builtin.apt:
    name:
      - jq
      - pip
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - golang
      - virtualenvwrapper
      - docker.io
      - docker-compose
      - rsyslog
      - ufw
      - openssl
      - osslsigncode
      - mingw-w64
      - amass
      - git
      - build-essential
      - apt-utils
      - cmake
      - libfontconfig1
      - libglu1-mesa-dev
      - libgtest-dev
      - libspdlog-dev
      - libboost-all-dev
      - libncurses5-dev
      - libgdbm-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - libsqlite3-dev
      - libbz2-dev
      - mesa-common-dev
      - qtbase5-dev
      - qtchooser
      - qt5-qmake
      - qtbase5-dev-tools
      - libqt5websockets5
      - libqt5websockets5-dev
      - qtdeclarative5-dev
      - qtbase5-dev
      - libqt5websockets5-dev
      - python3-dev
      - libboost-all-dev
      - nasm
      - binutils-mingw-w64
      - g++-mingw-w64
      - gpg
      - nim
      - seclists
      - ncat
      - burpsuite
    state: latest
  become: true

- name: Copy Virtualenvwrapper to correct directory
  ansible.builtin.copy:
    src: "/usr/share/virtualenvwrapper/virtualenvwrapper.sh"
    dest: "/usr/local/bin/virtualenvwrapper.sh"
    mode: "0755"
  become: true

- name: Add User to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "docker"
    append: yes
  become: true
