---
- name: Updating apt repo/cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  become: true

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: yes
    force_apt_get: yes
  become: true

- name: Uninstall some Packages
  ansible.builtin.apt:
    name:
      - enum4linux
    state: absent
  become: true

- name: Installing Packages
  ansible.builtin.apt:
    name:
      - jq
      - pip
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - golang
      - nextcloud-desktop
      - virtualenvwrapper
      - docker.io
      - docker-compose
      - rsyslog
      - ufw
      - openssl
      - osslsigncode
      - mingw-w64
      - amass
      - git
      - build-essential
      - apt-utils
      - cmake
      - libfontconfig1
      - libglu1-mesa-dev
      - libgtest-dev
      - libspdlog-dev
      - libboost-all-dev
      - libncurses5-dev
      - libgdbm-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - libsqlite3-dev
      - libbz2-dev
      - mesa-common-dev
      - qtbase5-dev
      - qtchooser
      - qt5-qmake
      - qtbase5-dev-tools
      - libqt5websockets5
      - libqt5websockets5-dev
      - qtdeclarative5-dev
      - qtbase5-dev
      - libqt5websockets5-dev
      - python3-dev
      - libboost-all-dev
      - nasm
      - binutils-mingw-w64
      - g++-mingw-w64
      - gpg
      - nim
      - seclists
      - ncat
      - dnsmasq
      - burpsuite
    state: latest
  become: true

- name: Copy Virtualenvwrapper to correct directory
  ansible.builtin.copy:
    src: "/usr/share/virtualenvwrapper/virtualenvwrapper.sh"
    dest: "/usr/local/bin/virtualenvwrapper.sh"
    mode: "0755"
  become: true

- name: Add User to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "docker"
    append: yes
  become: true

- name: Copy Dnsmasq conf file
  ansible.builtin.copy:
    src: "files/dnsmasq.conf"
    dest: "/etc/dnsmasq.conf"
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Enable and Start Dnsmasq Service
  ansible.builtin.systemd:
    name: dnsmasq
    state: started
    enabled: yes
  become: true

- name: List current connections
  ansible.builtin.shell: nmcli -t -f NAME connection show
  register: current_connections
  changed_when: false

- name: Delete connections that start with "Wired"
  ansible.builtin.shell: nmcli connection delete "{{ item }}"
  loop: "{{ current_connections.stdout_lines }}"
  when: "'Wired' in item"
  failed_when: false
  become: true

- name: Configure Network Interface to use dnsmasq
  community.general.nmcli:
    conn_name: "{{ item }}"
    type: ethernet
    dns4: 127.0.0.1
    dns4_ignore_auto: yes
    state: present
  with_items:
    - "{{ ansible_interfaces }}"
  when: "'eth' in item"
  ignore_errors: true
  become: true
