---
- name: Install Kerbrute
  ansible.builtin.shell: go install github.com/ropnop/kerbrute@master

- name: Download GO Git Repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
  loop:
    - { repo: "https://github.com/optiv/ScareCrow", location: "/opt/ScareCrow" }
  become: true

- name: Install ScareCrow
  ansible.builtin.shell:
    cmd: "go build ScareCrow.go"
    chdir: /opt/ScareCrow/
  become: true

- name: Install ligolo-ng
  ansible.builtin.shell:
    cmd: |
      go build -o agent cmd/agent/main.go
      go build -o proxy cmd/proxy/main.go
    chdir: /opt/ligolo-ng
  become: true

- name: Setup ligolo-ng
  ansible.builtin.shell:
    cmd: |
      ip tuntap add user {{ ansible_user_id }} mode tun ligolo
      ip link set ligolo up
  become: true
