---
- name: Install Kerbrute
  ansible.builtin.shell: go install github.com/ropnop/kerbrute@master

- name: Download GO Git Repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
  loop:
    - { repo: "https://github.com/optiv/ScareCrow", location: "/opt/ScareCrow" }
  become: true

- name: Install ScareCrow
  ansible.builtin.shell:
    cmd: "go build ScareCrow.go"
    chdir: /opt/ScareCrow/
  become: true
