---
- name: "Copy ZSHRC"
  copy:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_env.HOME }}"

- name: Clone zsh-autosuggestions repository
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Clone zsh-syntax-highlighting repository
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"